export const SECTOR_TAGS: string[] = [
  "agentic AI orchestration",
  "AI cloud infrastructure",
  "AI data center",
  "AI infrastructure monitoring",
  "AI security",
  "AI training data",
  "autonomous systems",
  "bitcoin mining",
  "cloud security",
  "cloud software",
  "contact center AI",
  "cybersecurity",
  "data analytics",
  "data engineering",
  "defense",
  "drones",
  "enterprise AI platform",
  "enterprise automation",
  "GPU compute",
  "GPU hosting",
  "hybrid cloud",
  "liquid cooling",
  "model evaluation",
  "neocloud",
  "observability",
  "RPA",
  "vulnerability management",
].sort((a, b) => a.localeCompare(b));
